@echo off
setlocal EnableDelayedExpansion

REM ===========================================================================
REM  Record Plotter - Win32 build
REM
REM    build.bat            release (optimised for size, static CRT)
REM    build.bat debug      unoptimised + /Zi, runtime checks on
REM    build.bat test       build and run the core tests (console exe)
REM    build.bat clean      remove the build directory
REM
REM  Set RP_STRICT=1 to make warnings fatal (/WX).
REM ===========================================================================

set ROOT=%~dp0
set OUT=%ROOT%build
set NAME=RecordPlot

if /i "%~1"=="clean" goto :do_clean

set MODE=release
if /i "%~1"=="debug" set MODE=debug
if /i "%~1"=="test"  set MODE=test

set "PF86=%ProgramFiles(x86)%"
if not defined PF86 set "PF86=%ProgramFiles%"

REM Set up MSVC unless already in a Developer Command Prompt.
if defined VCINSTALLDIR goto :msvc_ready
set "VSWHERE=%PF86%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" goto :no_vswhere

set VSPATH=
for /f "usebackq tokens=*" %%i in (`"%VSWHERE%" -latest -products * -property installationPath`) do set "VSPATH=%%i"
if not defined VSPATH goto :no_vs
set "VCVARS=%VSPATH%\VC\Auxiliary\Build\vcvars64.bat"
if not exist "%VCVARS%" goto :no_cpp

REM  Success is judged by VCINSTALLDIR, not by vcvars64's output.
call "%VCVARS%" >nul 2>&1
if not defined VCINSTALLDIR goto :vcvars_failed

:msvc_ready
if not exist "%OUT%" mkdir "%OUT%"

REM --- flags -----------------------------------------------------------------
REM  Release: static CRT, size-optimised, whole-program optimisation, no RTTI.
set STRICT=
if defined RP_STRICT set STRICT=/WX

set CFLAGS=/nologo /std:c++17 /W4 %STRICT% /permissive- /EHsc /utf-8 /DUNICODE /D_UNICODE /Zc:__cplusplus /I"%ROOT%src" /I"%OUT%"
set LFLAGS=/nologo /INCREMENTAL:NO /MACHINE:X64 /MANIFEST:NO
set HARDEN_C=/guard:cf
set HARDEN_L=/guard:cf /CETCOMPAT /DYNAMICBASE /HIGHENTROPYVA /NXCOMPAT /DEPENDENTLOADFLAG:0x800

if /i "%MODE%"=="debug" (
    set CFLAGS=%CFLAGS% /MTd /Od /Zi /RTC1 /D_DEBUG /Fd"%OUT%\%NAME%-debug.pdb"
    set LFLAGS=%LFLAGS% /DEBUG /PDB:"%OUT%\%NAME%-debug.pdb"
) else if /i "%MODE%"=="test" (
    set CFLAGS=%CFLAGS% /MTd /Od /Zi /RTC1 /D_DEBUG /Fd"%OUT%\tests.pdb"
    set LFLAGS=%LFLAGS% /DEBUG /PDB:"%OUT%\tests.pdb"
) else (
    set CFLAGS=%CFLAGS% /MT /O1 /Oi /Gy /Gw /GR- /GL /DNDEBUG /Zi /Fd"%OUT%\%NAME%.pdb" %HARDEN_C%
    set LFLAGS=%LFLAGS% /LTCG /OPT:REF /OPT:ICF /DEBUG /DEBUGTYPE:CV,FIXUP /PDB:"%OUT%\%NAME%.pdb" %HARDEN_L%
)

REM --- libraries -------------------------------------------------------------
REM  All ship with Windows.
set LIBS=user32.lib gdi32.lib d2d1.lib dwrite.lib dwmapi.lib comctl32.lib uxtheme.lib ole32.lib shell32.lib windowscodecs.lib advapi32.lib

if /i "%MODE%"=="test" goto :build_tests

REM --- sources ---------------------------------------------------------------
set SRC=
for %%f in ("%ROOT%src\*.cpp") do set SRC=!SRC! "%%f"
for %%f in ("%ROOT%src\core\*.cpp") do set SRC=!SRC! "%%f"
for %%f in ("%ROOT%src\ui\*.cpp") do set SRC=!SRC! "%%f"
if not defined SRC goto :no_sources

echo [build] %MODE% x64

REM --- build identity --------------------------------------------------------
REM  Writes the git commit ("+" if dirty) to build_id.h.
set "BUILD_ID=unknown"
for /f "delims=" %%h in ('git -C "%ROOT%." rev-parse --short^=8 HEAD 2^>nul') do set "BUILD_ID=%%h"
if not "%BUILD_ID%"=="unknown" (
    git -C "%ROOT%." diff --quiet HEAD >nul 2>nul || set "BUILD_ID=%BUILD_ID%+"
)
> "%OUT%\build_id.h" echo // GENERATED BY build.bat - do not edit, do not commit.
>>"%OUT%\build_id.h" echo #pragma once
>>"%OUT%\build_id.h" echo #define APP_BUILD_ID "%BUILD_ID%"
echo [build] build id %BUILD_ID%

echo [build] compiling resources
REM  app.rc and version.h are UTF-8.
rc /nologo /c65001 /i "%OUT%" /fo "%OUT%\%NAME%.res" "%ROOT%app.rc"
if errorlevel 1 goto :rc_failed

echo [build] compiling and linking
cl %CFLAGS% /Fo"%OUT%\\" /Fe"%OUT%\%NAME%.exe" %SRC% /link %LFLAGS% /SUBSYSTEM:WINDOWS "%OUT%\%NAME%.res" %LIBS%
if errorlevel 1 goto :cl_failed

echo.
for %%f in ("%OUT%\%NAME%.exe") do echo [build] OK  %%~nxf  %%~zf bytes
echo [build] dependencies:
dumpbin /nologo /dependents "%OUT%\%NAME%.exe" | findstr /i ".dll"
exit /b 0

REM --- tests -----------------------------------------------------------------
REM  Console test suite: src\core plus tests, run against tests\samples.
:build_tests
set TSRC=
for %%f in ("%ROOT%src\core\*.cpp") do set TSRC=!TSRC! "%%f"
for %%f in ("%ROOT%tests\*.cpp") do set TSRC=!TSRC! "%%f"
if not exist "%OUT%\test_obj" mkdir "%OUT%\test_obj"
echo [build] tests x64
cl %CFLAGS% /Fo"%OUT%\test_obj\\" /Fe"%OUT%\tests.exe" %TSRC% /link %LFLAGS% /SUBSYSTEM:CONSOLE %LIBS%
if errorlevel 1 goto :cl_failed
"%OUT%\tests.exe" "%ROOT%tests\samples"
exit /b %errorlevel%

:do_clean
if exist "%OUT%" rmdir /s /q "%OUT%"
echo [build] cleaned
exit /b 0

:no_vswhere
echo [build] ERROR: vswhere.exe not found at "%VSWHERE%".
echo [build]        Is Visual Studio (2017 or later) installed?
exit /b 1

:no_vs
echo [build] ERROR: vswhere found no Visual Studio installation.
exit /b 1

:no_cpp
echo [build] ERROR: vcvars64.bat not found under "%VSPATH%".
echo [build]        Install the "Desktop development with C++" workload.
exit /b 1

:vcvars_failed
echo [build] ERROR: vcvars64.bat did not initialise the MSVC environment.
echo [build]        Run it manually to see why:
echo [build]        "%VCVARS%"
exit /b 1

:no_sources
echo [build] ERROR: no .cpp files found under "%ROOT%src".
exit /b 1

:rc_failed
echo [build] ERROR: resource compilation failed.
exit /b 1

:cl_failed
echo [build] ERROR: compile/link failed.
exit /b 1
